FROM python:3.10-slim
RUN apt update && apt upgrade
COPY ./requirements/prod.txt /temp/requirements.txt
RUN pip install -r /temp/requirements.txt
COPY /src /app
WORKDIR /app
CMD chmod +x run.sh && ./run.sh