version: '3.8'

services:

  django:
    build: ./
    volumes:
      - ./src:/app
      - ./statics:/statics
    ports:
      - "8000:8000"
    env_file: ./.env_var
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file: ./.env_var
    volumes: 
     - dbdata:/var/lib/postgresql/data
    
  nginx:
    depends_on:
      - django
    image: nginx:1.25.1
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./statics:/etc/nginx/html/static

volumes:
  dbdata: