version: '3.8'

services:

  django:
    image: python:3.12-alpine
    command: ./run.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file: ./.env_var
    depends_on:
      - db

  postgres:
    image: postgres:15-alpine
    env_file: ./.env_var
    volumes: 
     - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: