# Generated by Django 4.2 on 2023-12-06 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('authors', models.CharField(max_length=300)),
                ('image', models.URLField(max_length=500)),
                ('preview_link', models.URLField(max_length=500, null=True)),
                ('date_published', models.DateField()),
                ('info_link', models.URLField(max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('categories', models.ManyToManyField(to='website.category')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.publisher')),
            ],
        ),
    ]
