# Generated by Django 4.2 on 2023-12-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_publisher_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='city',
        ),
    ]
